### ISSUE TITLE
Actions with spaces in the name are not found on execution

### ISSUE THREAD

**Issue by hfaas** [athombv/com.athom.homeyduino#46] opened 2018-08-06 20:21 UTC
Hi,

I noticed a bug, that on actions (and most likely also the capabilities and conditions), spaces are not properly handled by the homeyduino library.

When I register an action with a name containing spaces it is properly registered and visuallized in the flows of Homey. 

`Homey.addAction("Test Action 2", handleHomeyAction);`

Hoever on execution it fails to find the action because the %20 is not replaces back to spaces:

````
Handled as post request: /act/Test%20Action%202
api request
searching 'Test%20Action%202' of type 'act'...
POST REQUEST
host: 192.168.2.202:46639
content-length: 1
Connection: close
-----
-----
Handled as post request: /act/Test%20Action%202
api request
searching 'Test%20Action%202' of type 'act'...

````

I'm using library version 1.0.2
and ESP8266 device library 2.4.1

**Comment by gn0st1c** [comment] 2018-08-11 10:13
same as https://github.com/athombv/homey-arduino-library/issues/41

**Comment by jeroenvollenbrock** [comment] 2018-08-20 08:50
Closing as duplicate of athombv/homey-arduino-library#41

**Closed as completed by jeroenvollenbrock** 2018-08-20 08:50 UTC
